Food_delivery/Food_delivery/Areas/Admin/Controllers/ShopController.cs
using Food_delivery.Models.Data;
using Food_delivery.Models.ViewModels.Shop;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace Food_delivery.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ShopController : Controller
    {
        // GET: Admin/Shop/Categories
        public ActionResult Categories()
        {
            // Declare a list of models
            List<CategoryVM> categoryVMList;

            using (Food db = new Food())
            {
                // Init the list
                categoryVMList = db.Categories
                                .ToArray()
                                .OrderBy(x => x.Sorting)
                                .Select(x => new CategoryVM(x))
                                .ToList();
            }

            // Return view with list
            return View(categoryVMList);
        }
        
        // POST: Admin/Shop/AddNewCategory
        [HttpPost]
        public string AddNewCategory(string catName)
        {
            // Declare id
            string id;

            using (Food db = new Food())
            {
                // Check that the category name is unique
                if (db.Categories.Any(x => x.Name == catName))
                    return "titletaken";

                // Init DTO
                CategoryDTO dto = new CategoryDTO();

                // Add to DTO
                dto.Name = catName;
                dto.Slug = catName.Replace(" ", "-").ToLower();
                dto.Sorting = 100;

                // Save DTO
                db.Categories.Add(dto);
                db.SaveChanges();

                // Get the id
                id = dto.Id.ToString();
            }

            // Return id
            return id;
        }
        
        // POST: Admin/Shop/ReorderCategories
        [HttpPost]
        public void ReorderCategories(int[] id)
        {
            using (Food db = new Food())
            {
                // Set initial count
                int count = 1;

                // Declare CategoryDTO
                CategoryDTO dto;

                // Set sorting for each category
                foreach (var catId in id)
                {
                    dto = db.Categories.Find(catId);
                    dto.Sorting = count;

                    db.SaveChanges();

                    count++;
                }
            }

        }

        // GET: Admin/Shop/DeleteCategory/id
        public ActionResult DeleteCategory(int id)
        {
            using (Food db = new Food())
            {
                // Get the category
                CategoryDTO dto = db.Categories.Find(id);

                // Remove the category
                db.Categories.Remove(dto);

                // Save
                db.SaveChanges();
            }

            // Redirect
            return RedirectToAction("Categories");
        }

        // POST: Admin/Shop/RenameCategory
        [HttpPost]
        public string RenameCategory(string newCatName, int id)
        {
            using (Food db = new Food())
            {
                // Check category name is unique
                if (db.Categories.Any(x => x.Name == newCatName))
                    return "titletaken";

                // Get DTO
                CategoryDTO dto = db.Categories.Find(id);

                // Edit DTO
                dto.Name = newCatName;
                dto.Slug = newCatName.Replace(" ", "-").ToLower();

                // Save
                db.SaveChanges();
            }

            // Return
            return "ok";
        }

        // GET: Admin/Shop/AddProduct
        [HttpGet]
        public ActionResult AddProduct()
        {
            // Init model
            ProductVM model = new ProductVM();

            // Add select list of categories to model
            using (Food db = new Food())
            {
                model.Categories = new SelectList(db.Categories.ToList(), "Id", "Name");
            }

            // Return view with model
            return View(model);
        }

        // POST: Admin/Shop/AddProduct
        [HttpPost]
        public ActionResult AddProduct(ProductVM model, HttpPostedFileBase file)
        {
            // Check model state
            if (!ModelState.IsValid)
            {
                using (Food db = new Food())
                {
                    model.Categories = new SelectList(db.Categories.ToList(), "Id", "Name");
                    return View(model);
                }
            }

            // Make sure product name is unique
            using (Food db = new Food())
            {
                if (db.Products.Any(x => x.Name == model.Name))
                {
                    model.Categories = new SelectList(db.Categories.ToList(), "Id", "Name");
                    ModelState.AddModelError("", "That product name is taken!");
                    return View(model);
                }
            }

            // Declare product id
            int id;

            // Init and save productDTO
            using (Food db = new Food())
            {
                ProductDTO product = new ProductDTO();

                product.Name = model.Name;
                product.Slug = model.Name.Replace(" ", "-").ToLower();
                product.Description = model.Description;
                product.Price = model.Price;
                product.CategoryId = model.CategoryId;

                CategoryDTO catDTO = db.Categories.FirstOrDefault(x => x.Id == model.CategoryId);
                product.CategoryName = catDTO.Name;

                db.Products.Add(product);
                db.SaveChanges();

                // Get the id
                id = product.Id;
            }

            // Set TempData message
            TempData["SM"] = "You have added a product!";

            #region Upload Image

            // Create necessary directories
            var originalDirectory = new DirectoryInfo(string.Format("{0}Images\\Uploads", Server.MapPath(@"\")));

            var pathString1 = Path.Combine(originalDirectory.ToString(), "Products");
            var pathString2 = Path.Combine(originalDirectory.ToString(), "Products\\" + id.ToString());
            var pathString3 = Path.Combine(originalDirectory.ToString(), "Products\\" + id.ToString() + "\\Thumbs");
            var pathString4 = Path.Combine(originalDirectory.ToString(), "Products\\" + id.ToString() + "\\Gallery");
            var pathString5 = Path.Combine(originalDirectory.ToString(), "Products\\" + id.ToString() + "\\Gallery\\Thumbs");

            if (!Directory.Exists(pathString1))
                Directory.CreateDirectory(pathString1);

            if (!Directory.Exists(pathString2))
                Directory.CreateDirectory(pathString2);

            if (!Directory.Exists(pathString3))
                Directory.CreateDirectory(pathString3);

            if (!Directory.Exists(pathString4))
                Directory.CreateDirectory(pathString4);

            if (!Directory.Exists(pathString5))
                Directory.CreateDirectory(pathString5);

            // Check if a file was uploaded
            if (file != null && file.ContentLength > 0)
            {
                // Get file extension
                string ext = file.ContentType.ToLower();

                // Verify extension
                if (ext != "image/jpg" &&
                    ext != "image/jpeg" &&
                    ext != "image/pjpeg" &&
                    ext != "image/gif" &&
                    ext != "image/x-png" &&
                    ext != "image/png")
                {
                    using (Food db = new Food())
                    {
                        model.Categories = new SelectList(db.Categories.ToList(), "Id", "Name");
                        ModelState.AddModelError("", "The image was not uploaded - wrong image extension.");
                        return View(model);
                    }
                }

                // Init image name
                string imageName = file.FileName;

                // Save image name to DTO
                using (Food db = new Food())
                {
                    ProductDTO dto = db.Products.Find(id);
                    dto.ImageName = imageName;

                    db.SaveChanges();
                }

                // Set original and thumb image paths
                var path = string.Format("{0}\\{1}", pathString2, imageName);
                var path2 = string.Format("{0}\\{1}", pathString3, imageName);

                // Save original
                file.SaveAs(path);

                // Create and save thumb
                WebImage img = new WebImage(file.InputStream);
                img.Resize(200, 200);
                img.Save(path2);
            }

            #endregion

            // Redirect
            return RedirectToAction("AddProduct");
        }

        // GET: Admin/Shop/Products
        public ActionResult Products(int? page, int? catId)
        {
            // Declare a list of ProductVM
            List<ProductVM> listOfProductVM;

            // Set page number
            var pageNumber = page ?? 1;

            using (Food db = new Food())
            {
                // Init the list
                listOfProductVM = db.Products.ToArray()
                                  .Where(x => catId == null || catId == 0 || x.CategoryId == catId)
                                  .Select(x => new ProductVM(x))
                                  .ToList();

                // Populate categories select list
                ViewBag.Categories = new SelectList(db.Categories.ToList(), "Id", "Name");

                // Set selected category
                ViewBag.SelectedCat = catId.ToString();
            }

            // Set pagination

Food_delivery/Food_delivery/Controllers/PagesController.cs
using Food_delivery.Models.Data;
using Food_delivery.Models.ViewModels.Pages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Food_delivery.Controllers
{
    public class PagesController : Controller
    {
        // GET: Index/{page}
        public ActionResult Index(string page = "")
        {
            // Get/set page slug
            if (page == "")
                page = "home";

            // Declare model and DTO
            PageVM model;
            PageDTO dto;

            // Check if page exists
            using (Food db = new Food())
            {
                if (!db.ManagePages.Any(x => x.Slug.Equals(page)))
                {
                    return RedirectToAction("Index", new { page = "" });
                }
            }

            // Get page DTO
            using (Food db = new Food())
            {
                dto = db.ManagePages.Where(x => x.Slug == page).FirstOrDefault();
            }

            // Set page title
            ViewBag.PageTitle = dto.Title;

            // Check for sidebar
            if (dto.HasSidebar == true)
            {
                ViewBag.Sidebar = "Yes";
            }
            else
            {
                ViewBag.Sidebar = "No";
            }

            // Init model
            model = new PageVM(dto);

            // Return view with model
            return View(model);
        }

        public ActionResult PagesMenuPartial()
        {
            // Declare a list of PageVM
            List<PageVM> pageVMList;

            // Get all pages except home
            using (Food db = new Food())
            {
                pageVMList = db.ManagePages.ToArray().OrderBy(x => x.Sorting).Where(x => x.Slug != "home").Select(x => new PageVM(x)).ToList();
            }
            // Return partial view with list
            return PartialView(pageVMList);
        }

        public ActionResult SidebarPartial()
        {
            // Declare model
            SidebarVM model;

            // Init model
            using (Food db = new Food())
            {
                SidebarDTO dto = db.Sidebar.Find(1);

                model = new SidebarVM(dto);
            }

            // Return partial view with model
            return PartialView(model);
        }
    }
}

Food_delivery/Food_delivery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Ordered Food Online</title>
    <environment names="Development">
        <link rel="stylesheet" href="~/Content/bootstrap.css" />
        <link rel="stylesheet" href="~/Content/Site.css" />
    </environment>
    
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
   
</head>
<body>    
     
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="vertical-menu">                
                        <ul>
                            <li>LOGO</li>
                            <!--
                                <h2>@Html.ActionLink("FoodDelivery", "Index", "Pages", new { area = "" }, new { @class = "navbar-brand" }) </h2>
                              -->
                            @Html.Action("PagesMenuPartial", "Pages");
                            @if (Request.IsAuthenticated)
                            {
                                <li><a href="/account/logout">Logout</a></li>
                            }
                            else
                            {
                                if (ViewBag.Title == "Login")
                                {
                                    <li class="active"><a href="/account/login">Login</a></li>
                                }
                                else
                                {
                                    <li><a href="/account/login">Login</a></li>
                                }
                            }
                            @if (Request.IsAuthenticated && User.IsInRole("User"))
                            {
                                if (ViewBag.Title == "User Profile" || ViewBag.Title == "Orders")
                                {
                                    <li class="active">@Html.Action("UserNavPartial", "Account", new { area = "" })</li>
                                }
                                else
                                {
                                    <li>@Html.Action("UserNavPartial", "Account", new { area = "" })</li>
                                }
                            }
                        </ul>
                        @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <ul class="navbar-right adminarea">
                                <li>@Html.ActionLink("Admin Area", "Index", "Dashboard", new { area = "Admin" }, null) </li>
                            </ul>
                        }

                    </div>
                </div>
            <div class="col-sm-9">
                <div class="row">
                    <h1>ordered food online services</h1>
                </div>

                <div class="row">
                    <p>INTRODUCTION ABOUT OUR SERVICES AND PRODUCTS<hr/>INTRODUCTION ABOUT OUR SERVICES AND PRODUCTS<hr />
                        INTRODUCTION ABOUT OUR SERVICES AND PRODUCTS<hr />INTRODUCTION ABOUT OUR SERVICES AND PRODUCTS<hr />
                        INTRODUCTION ABOUT OUR SERVICES AND PRODUCTS<hr />
                        INTRODUCTION ABOUT OUR SERVICES AND PRODUCTS<hr /></p>
                </div>

                <div class="row">
                    <button class="btn">Start Your Order Here!</button>
                </div>
            </div>

            
            
            <!--
            <div class="body-content">
                <div class="row">

                <div class="ajaxbg">
                    <span><img src="~/Content/img/ajax-loader.gif" /></span>
                </div>
                        @if (ViewBag.Title != "Create Account" &&
                    ViewBag.Title != "Login" &&
                    ViewBag.Title != "User Profile" &&
                    ViewBag.Title != "Orders"
                    )
                       {
                        <div class="col-sm-6 col-sm-3">
                        @Html.Action("CategoryMenuPartial", "Shop")
                        </div>
                        }

                        @if (ViewBag.Title == "User Profile")
                    {
                    <div class="col-sm-6 col-sm-3">
                        <ul>
                            <li><a href="/account/orders">My Orders</a></li>
                        </ul>
                    </div>
                }
                @if (ViewBag.Title == "Orders")
            {
                    <div class="col-sm-6 col-sm-3">
                        <ul>
                            <li><a href="/account/user-profile">My Profile</a></li>
                        </ul>
                    </div>
                }
                @if (ViewBag.Sidebar == "Yes")
            {
                    <div class="col-sm-5 col-sm-4">
                        @RenderBody()
                    </div>
                    <div class="col-col-sm-6 col-sm-3">
                        @Html.Action("SidebarPartial", "Pages")
                    </div>
                }
                else
                {
                    <div class="col-sm-5 col-sm-4">
                        @RenderBody()
                    </div>
                }
                </div>               
                
            </div>
            -->
            <hr />
            <footer>
                <p><br /> <br /><br/> &copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>
    </div>



    

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    
</body>
</html>